version: 2.1
orbs:
  node: circleci/node@3.0.0
steps:
  - restore_cache:
    keys:
       - node-v1-{{ checksum "package-lock.json" }}
       - node-v1-
workflows:
  node-tests:
    jobs:
      - node/test
